name: Car Sales Analysis

on:
  push:
    branches: [ main ]

jobs:
  Car_sales:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib

    - name: Run analysis
      run: python Car sales.py

